In [1]:
import os
import pprint
import tempfile

from typing import Dict, Text

import pandas as pd
import numpy as np
import tensorflow as tf
import tensorflow_recommenders as tfrs

2023-07-24 10:23:50.308075: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-24 10:23:50.620484: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-07-24 10:23:50.620499: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-07-24 10:23:51.503873: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
path = '/home/vern/aiedge_capstone/aie_recsys_cap/STEAM/model'

# Load it back; can also be done in TensorFlow Serving.
loaded = tf.saved_model.load(path)

2023-07-24 10:25:34.501883: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-07-24 10:25:34.501900: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-07-24 10:25:34.501915: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (gram17): /proc/driver/nvidia/version does not exist
2023-07-24 10:25:34.502077: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
# K = max 10 how many recommendations, my_user_id
K = 5
my_user_id = '76767'

# Pass a user id in, get top predicted game titles back.
scores, titles = loaded([my_user_id])

print(f"Recommendations for user_id {my_user_id}: {titles[0][:K]}")

Recommendations for user_id 76767: [b'304050' b'335330' b'346110' b'99900' b'363970']


In [9]:
# K = max 10 how many recommendations, my_user_id
K = 5
my_user_id = '5250'

# Pass a user id in, get top predicted game titles back.
scores, titles = loaded([my_user_id])

print(f"Recommendations for user_id {my_user_id}: {titles[0][:K]}")

Recommendations for user_id 5250: [b'242720' b'10' b'80' b'60' b'30']


In [14]:
titles[0]

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'242720', b'10', b'80', b'60', b'30', b'40', b'570', b'400',
       b'420', b'380'], dtype=object)>

In [12]:
scores[0][:K]

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([2.2246885, 2.2172954, 2.1896472, 2.1394496, 2.0743012],
      dtype=float32)>

# Test SCANN index

In [15]:
path2 = '/home/vern/aiedge_capstone/aie_recsys_cap/STEAM/scann_model'

# Load it back; can also be done in TensorFlow Serving.
loaded2 = tf.saved_model.load(path2)

In [16]:
# K = max 10 how many recommendations, my_user_id
K = 5
my_user_id = '76767'

# Pass a user id in, get top predicted game titles back.
scores, titles = loaded2([my_user_id])

print(f"Recommendations for user_id {my_user_id}: {titles[0][:K]}")

Recommendations for user_id 76767: [b'335330' b'363970' b'99900' b'304050' b'311210']


In [17]:
scores[0][:K]

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.2236708 , 0.96561706, 0.9048491 , 0.8604841 , 0.83050716],
      dtype=float32)>